name: Publish And Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    branches:
      - main
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: blog
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Dependencies And Update Theme 🔧
        run: |
          npm install
      - name: Sync Markdown 🔧
        env:
          YUQUE_USERNAME: ${{ vars.YUQUE_USERNAME }}
          YUQUE_PASSWORD: ${{ vars.YUQUE_PASSWORD }}
          YUQUE_LOGIN: ${{ vars.YUQUE_LOGIN }}
          YUQUE_REPO: ${{ vars.YUQUE_REPO }}
        run: |
          npm run sync
      - name: Build 🔧
        run: |
          npm run docs:build
      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
#      - name: Rename Folder Name 🔧
#        run: |
#          mv ./public/ ./resonance.fun/
#      - name: SSH Server Deploy 🚀
#        uses: kostya-ten/ssh-server-deploy@v4
#        with:
#          host: ${{ secrets.SSH_SERVER }}
#          port: 22
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          scp_source: ./resonance.fun/
#          scp_target: /www/wwwroot/

